#!groovy

def dockerHost = 'tcp://dind.default.svc.cluster.local:2375'
def projectVersion
def projectName
def publishImageTag

node('nodejs') {

  stage('build') {
    git url: 'https://github.com/afoninsky/micro-test'
    projectName = sh(returnStdout: true, script: 'node -pe "require(\'./package.json\').name"').trim()
    projectVersion = sh(returnStdout: true, script: 'node -pe "require(\'./package.json\').version"').trim()
    publishImageTag = "us.gcr.io/spair-api/${projectName}:${projectVersion}"
    sh "docker -H ${dockerHost} run -t ${publishImageTag} . "
  }

  stage('test') {
    sh "docker -H ${dockerHost} exec ${publishImageTag} npm test"
    //2do: deply test service and perform intergration test
    //2do: compare coverage with previous value
  }

  stage('push') {
    sh "docker -H ${dockerHost} push ${publishImageTag}"
  }
}
